create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    login text null,
    password text null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.students (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    names text null,
    constraint students_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.characters (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    character_name text null,
    greeting text null,
    constraint characters_pkey primary key (id)
  ) tablespace pg_default;